import { Station } from './types';

// Station autocomplete is served from this bundled list instead of the API.
// Station codes are static data - burning API quota on them is wasteful.
export const STATIONS: Station[] = [
  { code: 'NDLS', name: 'New Delhi' },
  { code: 'DLI', name: 'Delhi Jn' },
  { code: 'NZM', name: 'Hazrat Nizamuddin' },
  { code: 'ANVT', name: 'Anand Vihar Terminal' },
  { code: 'MMCT', name: 'Mumbai Central' },
  { code: 'CSMT', name: 'Mumbai CSM Terminus' },
  { code: 'LTT', name: 'Lokmanya Tilak Terminus' },
  { code: 'BDTS', name: 'Bandra Terminus' },
  { code: 'BVI', name: 'Borivali' },
  { code: 'TNA', name: 'Thane' },
  { code: 'KYN', name: 'Kalyan Jn' },
  { code: 'PUNE', name: 'Pune Jn' },
  { code: 'HWH', name: 'Howrah Jn' },
  { code: 'SDAH', name: 'Sealdah' },
  { code: 'KOAA', name: 'Kolkata' },
  { code: 'MAS', name: 'Chennai Central' },
  { code: 'MS', name: 'Chennai Egmore' },
  { code: 'SBC', name: 'KSR Bengaluru City Jn' },
  { code: 'YPR', name: 'Yesvantpur Jn' },
  { code: 'SC', name: 'Secunderabad Jn' },
  { code: 'HYB', name: 'Hyderabad Deccan' },
  { code: 'ADI', name: 'Ahmedabad Jn' },
  { code: 'ST', name: 'Surat' },
  { code: 'BRC', name: 'Vadodara Jn' },
  { code: 'RTM', name: 'Ratlam Jn' },
  { code: 'INDB', name: 'Indore Jn' },
  { code: 'BPL', name: 'Bhopal Jn' },
  { code: 'JBP', name: 'Jabalpur Jn' },
  { code: 'KOTA', name: 'Kota Jn' },
  { code: 'JP', name: 'Jaipur Jn' },
  { code: 'JU', name: 'Jodhpur Jn' },
  { code: 'UDZ', name: 'Udaipur City' },
  { code: 'AII', name: 'Ajmer Jn' },
  { code: 'AGC', name: 'Agra Cantt' },
  { code: 'MTJ', name: 'Mathura Jn' },
  { code: 'GWL', name: 'Gwalior Jn' },
  { code: 'VGLJ', name: 'Virangana Lakshmibai Jhansi' },
  { code: 'CNB', name: 'Kanpur Central' },
  { code: 'LKO', name: 'Lucknow NR' },
  { code: 'LJN', name: 'Lucknow Jn' },
  { code: 'PRYJ', name: 'Prayagraj Jn' },
  { code: 'BSB', name: 'Varanasi Jn' },
  { code: 'DDU', name: 'Pt. DD Upadhyaya Jn' },
  { code: 'GKP', name: 'Gorakhpur Jn' },
  { code: 'PNBE', name: 'Patna Jn' },
  { code: 'RJPB', name: 'Rajendra Nagar Terminal' },
  { code: 'GAYA', name: 'Gaya Jn' },
  { code: 'DHN', name: 'Dhanbad Jn' },
  { code: 'RNC', name: 'Ranchi Jn' },
  { code: 'TATA', name: 'Tatanagar Jn' },
  { code: 'BBS', name: 'Bhubaneswar' },
  { code: 'PURI', name: 'Puri' },
  { code: 'VSKP', name: 'Visakhapatnam Jn' },
  { code: 'BZA', name: 'Vijayawada Jn' },
  { code: 'TPTY', name: 'Tirupati' },
  { code: 'GNT', name: 'Guntur Jn' },
  { code: 'WL', name: 'Warangal' },
  { code: 'KZJ', name: 'Kazipet Jn' },
  { code: 'NGP', name: 'Nagpur Jn' },
  { code: 'BPQ', name: 'Balharshah Jn' },
  { code: 'R', name: 'Raipur Jn' },
  { code: 'BSP', name: 'Bilaspur Jn' },
  { code: 'ET', name: 'Itarsi Jn' },
  { code: 'AMLA', name: 'Amla Jn' },
  { code: 'AK', name: 'Akola Jn' },
  { code: 'BSL', name: 'Bhusaval Jn' },
  { code: 'MMR', name: 'Manmad Jn' },
  { code: 'NK', name: 'Nashik Road' },
  { code: 'SUR', name: 'Solapur Jn' },
  { code: 'MRJ', name: 'Miraj Jn' },
  { code: 'KOP', name: 'Kolhapur SCSMT' },
  { code: 'MAO', name: 'Madgaon Jn' },
  { code: 'UBL', name: 'SSS Hubballi Jn' },
  { code: 'MYS', name: 'Mysuru Jn' },
  { code: 'MAQ', name: 'Mangaluru Central' },
  { code: 'CLT', name: 'Kozhikode' },
  { code: 'ERS', name: 'Ernakulam Jn' },
  { code: 'TVC', name: 'Thiruvananthapuram Central' },
  { code: 'TCR', name: 'Thrissur' },
  { code: 'CBE', name: 'Coimbatore Jn' },
  { code: 'ED', name: 'Erode Jn' },
  { code: 'SA', name: 'Salem Jn' },
  { code: 'TPJ', name: 'Tiruchchirappalli Jn' },
  { code: 'MDU', name: 'Madurai Jn' },
  { code: 'TEN', name: 'Tirunelveli Jn' },
  { code: 'CAPE', name: 'Kanniyakumari' },
  { code: 'RMM', name: 'Rameswaram' },
  { code: 'ASR', name: 'Amritsar Jn' },
  { code: 'JUC', name: 'Jalandhar City' },
  { code: 'LDH', name: 'Ludhiana Jn' },
  { code: 'UMB', name: 'Ambala Cantt Jn' },
  { code: 'CDG', name: 'Chandigarh' },
  { code: 'KLK', name: 'Kalka' },
  { code: 'JAT', name: 'Jammu Tawi' },
  { code: 'SVDK', name: 'SMVD Katra' },
  { code: 'DDN', name: 'Dehradun' },
  { code: 'HW', name: 'Haridwar Jn' },
  { code: 'MB', name: 'Moradabad Jn' },
  { code: 'BE', name: 'Bareilly Jn' },
  { code: 'GHY', name: 'Guwahati' },
  { code: 'NJP', name: 'New Jalpaiguri Jn' },
  { code: 'KGP', name: 'Kharagpur Jn' },
  { code: 'ASN', name: 'Asansol Jn' },
  { code: 'MFP', name: 'Muzaffarpur Jn' },
  { code: 'BJU', name: 'Barauni Jn' },
  { code: 'KIR', name: 'Katihar Jn' },
  { code: 'DBG', name: 'Darbhanga Jn' },
  { code: 'CPR', name: 'Chhapra Jn' },
  { code: 'BUI', name: 'Ballia' },
  { code: 'GCT', name: 'Ghazipur City' },
  { code: 'RXL', name: 'Raxaul Jn' },
  { code: 'BKN', name: 'Bikaner Jn' },
  { code: 'BME', name: 'Barmer' },
  { code: 'BVC', name: 'Bhavnagar Terminus' },
  { code: 'RJT', name: 'Rajkot Jn' },
  { code: 'JAM', name: 'Jamnagar' },
  { code: 'OKHA', name: 'Okha' },
  { code: 'GIMB', name: 'Gandhidham Jn' },
  { code: 'PBR', name: 'Porbandar' },
];

export function searchStationsLocal(query: string): Station[] {
  const q = query.trim().toLowerCase();
  if (!q) return STATIONS;
  const starts: Station[] = [];
  const contains: Station[] = [];
  for (const s of STATIONS) {
    const name = s.name.toLowerCase();
    const code = s.code.toLowerCase();
    if (name.startsWith(q) || code === q) starts.push(s);
    else if (name.includes(q) || code.startsWith(q)) contains.push(s);
  }
  return [...starts, ...contains];
}
